package com.bnta.chocolate.models;

public class ChocolateDto {

    //THIS WAS JUST MEANT TO LOOK LIKE THE CHOCOLATE MODEL EXCEPT WITH NO ANNOTATIONS,
    // ESTATE WITH INT DATA TYPE AND ONLY AN EMPTY CONSTRUCTOR
}
